"""add task_id to execution_events

Revision ID: 15a2c3a6056b
Revises: 4c8eaba370ee
Create Date: 2026-08-30 19:59:10.522071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a2c3a6056b'
down_revision: Union[str, Sequence[str], None] = '4c8eaba370ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_events', sa.Column('task_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_execution_events_task_id'), 'execution_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_execution_events_timestamp'), 'execution_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_execution_events_timestamp'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_task_id'), table_name='execution_events')
    op.drop_column('execution_events', 'task_id')
    # ### end Alembic commands ###
