"""Add options to task

Revision ID: 4c8eaba370ee
Revises: 97025c4b6d05
Create Date: 2026-08-30 19:07:30.204195

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c8eaba370ee'
down_revision: Union[str, Sequence[str], None] = '97025c4b6d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'options')
    # ### end Alembic commands ###
